---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - production-stack.vllm.ai
  resources:
  - staticroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - production-stack.vllm.ai
  resources:
  - staticroutes/finalizers
  verbs:
  - update
- apiGroups:
  - production-stack.vllm.ai
  resources:
  - staticroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serving.vllm.ai
  resources:
  - productionstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.vllm.ai
  resources:
  - productionstacks/finalizers
  verbs:
  - update
- apiGroups:
  - serving.vllm.ai
  resources:
  - productionstacks/status
  verbs:
  - get
  - patch
  - update
